[general]
import = [
    "~/.config/alacritty/themes/_active.toml"
]

[font]
size = 11.0

[font.normal]
# family = "Ioskeley Mono"
family = "Mononoki Nerd Font"
# family = "InconsolataGo Nerd Font"
# family = "Monoid Nerd Font"
# family = "IosevkaTerm Nerd Font"
# family = "IosevkaTermSlab Nerd Font Mono"
# family = "Hasklug Nerd Font"
# family = "SauceCodePro Nerd Font"
# family = "MesloLGLDZ Nerd Font"
# family = "MesloLGS Nerd Font"
# family = "MesloLGL Nerd Font"
# family = "MesloLGM Nerd Font"

style = "Regular"

[env]
TERM = "xterm-256color"
