[general]
import = [
    "~/.config/alacritty/themes/_active.toml"
]

[font]
size = 10.0

[font.normal]
# family = "Ioskeley Mono"
# family = "Mononoki Nerd Font Mono"
# family = "InconsolataGo Nerd Font Mono"
# family = "Monoid Nerd Font Mono"
# family = "IosevkaTerm Nerd Font Mono"
# family = "IosevkaTermSlab Nerd Font Mono"
family = "Hasklug Nerd Font Mono"
style = "Regular"

[env]
TERM = "xterm-256color"
