#!/bin/bash
############################
#
############################

tmux set -g @colors-solarized 'dark' 
~/dotfiles/set-solarized-terminal-theme.sh dark >/dev/null 2>&1
tmux source-file ~/.tmux.conf >/dev/null 2>&1
~/dotfiles/vim-servers-theme.sh dark >/dev/null 2>&1
  



